trigger:
  - main

pool:
  name: my-agent-win

stages:


- stage: Validate
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: TerraformTaskV4@4
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/environments/prod
        backendServiceArm: azure-prod-svc
        backendAzureRmResourceGroupName: tfstate-rg
        backendAzureRmStorageAccountName: tfstateprod001
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: prod/infra.tfstate

    - task: TerraformTaskV4@4
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/environments/prod


- stage: Plan
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(System.DefaultWorkingDirectory)/environments/prod
        environmentServiceNameAzureRM: azure-prod-svc
        commandOptions: "-var-file=prod.tfvars"


- stage: Apply
  dependsOn: Plan
  jobs:
  - deployment: Apply
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformTaskV4@4
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: $(System.DefaultWorkingDirectory)/environments/prod
              environmentServiceNameAzureRM: azure-prod-svc
              commandOptions: "-auto-approve -var-file=prod.tfvars"
